### ISSUE TITLE
Effects: Cannot Parse Bonus Damage / Error with damage formula involving brackets and operators

### ISSUE THREAD

**Issue by DreamingHero1997** [teroparvinen/foundry-wire#17]
It seems WIRE cannot parse the bonus damage in effects if it involves operators like in the example below
![image](https://user-images.githubusercontent.com/84264700/209481648-8c78cbe2-7b06-4af9-b129-ed02a17ffb97.png)
It returns the following in the console 
![image](https://user-images.githubusercontent.com/84264700/209481661-f739bd31-e2af-4a9b-9b3f-16773b1d2342.png)
With the brackets involved it seems no roll occurs at all, without the brackets it does roll damage but not the bonus damage and returns: _**Could not parse bonus damage!**_
This seems to only be an issue when implemented into effects, when implemented into a damage formula of an item itself no problems occur.

**Comment by teroparvinen** [comment]
This is kind of a known issue that is both hard to solve and not very high priority (with other things currently needing work).

The basic reason is that because WIRE tracks all damage by damage type, things have to be rather precise and the roll parsing logic in core Foundry is not great. Damage parts from the item damage rows is usually good, but things that come from effects (as you have noticed) need to parse the flavor correctly to attribute damage type. I can't remember the details well enough right now, but if you try to put flavor in square brackets after a formula such as what you have in the example, Foundry has problems attributing it to the correct place. I had to write some custom logic to help Foundry parse the rolls to at least an acceptable degree, and that custom logic is what is failing here probably.

An example of this would be Divine Smite that needs to give the damage bonus as `+((@config.spellLevel+1)d8)[radiant]`. The placement of the parentheses helps the parser, so you should try and see if something like that helps. Also keep in mind that any unflavored damage is attributed to the primary damage type, but even in this case the result might theoretically be something like `1d8 + @mod` (slashing) from the item, `+1d6[fire]` from one effect bonus, `+2` from another effect bonus (which would then be counted as slashing) and `+((@target.type.undead)d8)[radiant]` from a third. This is of course probably not a real world scenario, but I hope you can see where it gets complicated.

Also, `@item.level` probably does not do what you expect (i.e. upcast things). WIRE always gets this from the item (i.e. does no special processing, for Magic Missile it is always 1), and puts the the final upcast level into `@config.spellLevel` (if you upcast Magic Missile to third level, this would be 3) and the number of upcast levels into `@config.upcastLevel` (if you upcast Magic Missile to third level, this would be 2).

If this does not help you in your particular case, could you describe what you're doing and I could perhaps help or see if it is a case I need to support better?

**Comment by DreamingHero1997** [comment]
Okay so I've tried re-arranging and putting brackets in different places to make it work, it now looks like this.
![image](https://user-images.githubusercontent.com/84264700/209554572-52e12c2d-b8ba-4a37-b14e-71ac73a3678d.png)
It seems to work correctly in this way, I've tried your @config.spellLevel but it seems in my games it just returns with 0 in every case, although do mind that the effect is not on a spell but on a feature so that might tie into it, although I also tried using it in a fireball spell's damage formula but it also returned a 0.

But I seem to have gotten it to work so I'm pretty happy, keep up the great work with the module I think it's gonna be the future of Foundry's automation with how amazing the features are.
