### ISSUE TITLE
Healing as an effect damage option

### ISSUE THREAD

**Issue by DreamingHero1997** [teroparvinen/foundry-wire#29]
Hey I was wondering if there is a way to make an effect that could add healing or temporary healing whenever damage/healing is rolled, I tried using [healing] and [healing(temp)] but those don't work.

**Comment by teroparvinen** [comment]
You can probably do what you want simply by using `system.bonuses.heal.damage`. That adds a character specific bonus die/modifier whenever a healing spell is cast and the amount of healing it does is determined. It will only happen if the action is specified as healing:

![image](https://user-images.githubusercontent.com/1235386/210975424-1794674a-bc69-4a5d-9e04-b0bd5c887ec2.png)

Having said that, I did notice that WIRE does not extend this particular bit with `healing` and `temphp` (the correct damage type for temp hp), so parsing the damage bonus would fail if the flavor is added (so in this case, use something like "+1d4", not "+1d4[healing]". I'm not sure what the correct solution is off the bat because adding healing to a damage formula is generally nonsensical. Thanks for bringing this up however, I will have a more careful look at it.

It can also sometimes be confusing when some of the modifiers work by action type (`mwak`, `rsak`, `heal` etc.) and others by damage type (`acid`, `fire`, `healing` etc.).

**Comment by DreamingHero1997** [comment]
Yeah my particular use case is an item that adds temporary HP when a character heals with a spell, I can also just make a separate roll for it, an effect would just make it easier for the player.

**Comment by teroparvinen** [comment]
Right... This will work by entering something like `+1d4[temphp]` in the `system.bonuses.heal.damage`change after the next WIRE update.

**Comment by DreamingHero1997** [comment]
Thanks, looking forward to it, keep up the amazing work :D
