### ISSUE TITLE
[enhancement] automatically apply "wounded" and "unconscious" conditions

### ISSUE THREAD

**Issue by cstby** [teroparvinen/foundry-wire#3]
I'm not sure whether the intended scope of WIRE includes automatically applying the wounded and unconscious conditions. However, I felt the absence of this automation when switching from midi-qol. Automatic application of the wounded condition in particular helps to create a more immersive combat experience for players. If this isn't the right module for it, I'd be interested to find the right home for this functionality.

Expected behavior:
- When any creature's hp is reduced to less than half of its max hp, then the creature should receive the wounded condition.
- Given any creature with the wounded condition: when the creature's hp is increased to more than half of its max hp, then the creature's the wounded condition should be removed.
- When a player character's hp is reduced to zero, then the player character should receive the unconscious condition.
- Given a player character with the unconscious condition: when the player character's hp is increased to 1 or greater, then the unconscious condition should be removed.

**Comment by teroparvinen** [comment]
This is a lack of documentation. This is currently done using Convenient Effects, so install that. I don't currently have plans to roll a status handler into WIRE because CE does all that is needed.

It has a wounded condition that is applied at 50%. If you create a condition called "Damaged", it will be applied whenever the NPC takes a wound, i.e. is damaged at least 1 HP. Unconscious should also work.

Let me know if there's a problem and I'll reopen the issue.
