### ISSUE TITLE
[Bug] Magical Weapons not ignoring resistance

### ISSUE THREAD

**Issue by Geekswordsman** [teroparvinen/foundry-wire#45]
**D&D** 5e v2.1.5
**WIRE** v0.10.12

Barebone world, only WIRE enabled.  A creature with immunities to Bludgeoning, Piercing, and Slashing from attacks that are not magical still has resistances applied when hit with a weapon that has the magical property.

See attached.

![image](https://user-images.githubusercontent.com/41522046/220676002-180e2891-cd1a-4d1e-a06f-99d882020587.png)
![image](https://user-images.githubusercontent.com/41522046/220676135-28acbeed-8470-4cc1-84cb-1acaeafee799.png)
![image](https://user-images.githubusercontent.com/41522046/220676205-ea142831-ab10-489c-a5d1-82eb26b91b82.png)

**Comment by DreamingHero1997** [comment]
To add to this, it seems this needs to be fixed for all physical weapon properties and the physical weapon properties bypassing should also work the WIRE's flags.wire.damagereduction.bludgeoning/physical/piercing/slashing types.

**Comment by teroparvinen** [comment]
> [...] the physical weapon properties bypassing should also work the WIRE's flags.wire.damagereduction.bludgeoning/physical/piercing/slashing types.

This part is problematic because the bypass flags are specific to damage immunity, damage resistance and damage vulnerability. They might differ and there is no way to map them to the damage reduction options available through the flag. I will probably keep this so that if a weapon has the "Magical" property, it will bypass physical damage reduction.
