### ISSUE TITLE
[bug] two saving throws presented to players

### ISSUE THREAD

**Issue by cstby** [teroparvinen/foundry-wire#5]
In some cases, two saving throws are displayed to a player when only one is displayed to the GM.

Below, I've used Whelm from a Water Elemental, and two prompts for a saving throw appeared in the player chat. 

![image](https://user-images.githubusercontent.com/45189177/206095686-e59be30b-abdd-4834-8eba-5d54aacd9ce7.png)

**Comment by teroparvinen** [comment]
I tried to replicate this but couldn't. I would like to recommend you disable all non-required modules and see if this persists. I got a report of a v10 update regression that manifests if you do not have DAE installed, so leave that on.

Pay extra attention to any modules that might create chat items or modify chat messages.

Also include any error messages you might get in the console (F12 inside Foundry on windows, show developer tools on a browser).

Your screenshot looks like this has been rolled as the GM (you have the 3 small GM control icons after "Strength Saving Throw (DC15)" but the messages seem to have the player visible texture as background. The first idea here is a module conflict.

**Comment by cstby** [comment]
I created a new world to test with minimal modules. Here's my current module list:
- DAE 10.0.13
- libWrapper 1.12.11.0
- socketlib 1.0.12
- WIRE 0.10

I'm getting the same behavior. No error messages in the console.

Could this be because I have "public roll" selected on the GM side?

**Comment by teroparvinen** [comment]
> Could this be because I have "public roll" selected on the GM side?

This seems to be it. For the time being I recommend using private GM rolls.

I'm thinking how to fix this and my initial thought is to enforce the way it was designed to be used, i.e. if a WIRE roll is made with "Public roll" selected, it will be turned into a private GM roll anyway.

So my question is, since you are apparently using public GM rolls in your game, how would you want this to function, and is there a case that would be a nuisance to you the way it currently works with private GM rolls?

**Comment by cstby** [comment]
Thanks for that clarification. First, I'll give a little context on why I'm using public rolls. Then I'll describe how this module can better fit my use case.

I roll in public because it better engages my players, many of whom are new to D&D. They feel a stronger sense of danger and tension because their fate is completely up to the dice. When they fight monsters, they are usually seeing that monster for the first time. When they can see the monster art, monster name, and the ability descriptions, those monsters are more memorable to them. Rolling in public also helps my players better understand the flow of combat. I've tried rolling in private, and I've found rolling in public to be much more effective at my table.

Many DMs roll in private, and I completely respect that. I understand that metagaming can be a big problem at some tables with more experienced players. That said, they are both viable ways to play the game. I'd find it unfortunate if your module only supported one style of play. At least in my case, I couldn't give up the benefits of public rolling for the benefits that this module provides.

This module supports public rolling fairly well right now. I've only found a few places that are a nuisance:
- The example at the top of the thread where the saving throw is prompted to the player twice. In this case, I would expect the NPC ability to be sent to both the player and GM chat. I would expect WIRE send a private GM chat with the current capabilities: force success/failure, roll all, roll npcs. I would also expect WIRE to send one or more public messages to prompt the affected players for saving throws (ideally showing the DC). The current behavior is very close to this ideal. The only changes I'd want are for the GM interface to be made private, and to add the DC to the player public messages.
- Currently the NPC turn annoucements are private to the GM. I'd want these to be public chats.
- Already mentioned in https://github.com/teroparvinen/foundry-wire/issues/1: the AC of NPCs should be hidden even when the GM initiates the roll.

**Comment by teroparvinen** [comment]
Thanks for the write up. I already managed to come up with a version that handles public GM rolls so that the GM version of the card remains very similar to the private case, but shows more stuff on the player version. This handles AC the way you need I think.

I don't have very many settings in the module at the moment, and that is due to two things. First, I wanted to roll it out the way I imagined it to be and second (and more important) I wanted to get it somewhat done so I know how it should work myself. I have lots of stuff already planned that goes into optional settings, and showing save DCs to players is already on that list. When that option is available, it should address your needs for this I think. I will add NPC turn announcements to that list as well so you can use the setting when I get it done.

WIRE handles chat messages a bit differently because the item cards are interactive and there needs to be a separate GM version. This makes some things tricky and I want to make sure I don't break things so while this might go slower than some like, I will hopefully get there in time.

Have a look at the next version that will come out after I get this thing tested and let me know how it feels.
