### ISSUE TITLE
Compatibility with Automated Animations

### ISSUE THREAD

**Issue by Fatalmac77** [teroparvinen/foundry-wire#60]
Foundry version 11.313, WIRE version 0.11.3
I have a problem with Automated Animations displaying effects correctly. The animations are multiplied and, for example, instead of animating one sword attack, a dozen of them are displayed on the token. As if the Sequencer was repeating the same process several times? Sounds effects work normally. 

In the console I have the message:

![konsola](https://github.com/teroparvinen/foundry-wire/assets/128055466/c6f83c77-1a4f-4a2f-8aea-0d5dda9415d6)

List of active modules:

![moduly](https://github.com/teroparvinen/foundry-wire/assets/128055466/5fdf0223-c76a-4e3b-9cc5-1b9c4e571380)

The WIRE module is fantastic. I hope it will develop.

**Comment by teroparvinen** [comment]
This turned out to be a bit more complicated than expected. Some recent changes to WIRE (including better compatibility with Build-A-Bonus) have made AA and WIRE somewhat incompatible and the three can't really function together with changes to WIRE only. I have submitted a compatibility patch to AA, but it needs to be accepted and published before the issue is fully fixed. I just released a small fix on the WIRE side, so this should be fully addressed as soon as AA is updated to include the fix.
