### ISSUE TITLE
[Feature Request] GM hit confirmation bypass

### ISSUE THREAD

**Issue by roguedevjake** [teroparvinen/foundry-wire#9]
**Issue**
Clicking to confirm if an attack hits or misses before being able to roll for damage as a GM when using NPCs introduces redundant clicks.

**Example Impact**
I just ran a combat with 24 creatures with multi attack, followed by one with 13 creatures with multi attack. That is a lot of extra clicks.

**Proposed Solution**
Have the damage buttons always appear for the GM and if clicked confirm the attack as a hit. This way hit/miss mechanics and layout are preserved but can be intuitively streamlined in play.

**Comment by teroparvinen** [comment]
Although this functionality is offered by other modules, it is frankly outside the scope of WIRE. I understand what you're saying and will keep it in mind, as things change and you can never rule out something for good.

The very technical fundamentals of the module are based on an item specific flow of events that can be customized. This means the system is flexible enough to support things that have an attack roll but no damage (like Ray of Enfeeblement) or to apply effects first and damage (or negative damage, healing) second (like Aid). This also means that when an attack roll is processed, the system doesn't exactly know that a damage roll is coming. So this is both a fundamental technical issue and a design issue at the same time.

I also have an "each roll is sacred" policy which means that damage rolls aren't rolled "in case". This is just not that module. If you are running Dice So Nice you probably also noticed that nothing happens until the dice have landed. This is also one of the lines I'm not willing to cross although it could potentially save minutes in a combat with more than 48 attacks to process per round.

I would rather solve your issue by making optional hotkeys that can be bound to roll damage, maybe to roll the "next roll" (be it damage, saves or whatever in case deducing that is possible) and confirm a hit (i.e. two keys, confirm and reject and possibly a third, confirm if would hit AC, reject otherwise). These are examples of the kind of power user features I would like to support.

My hope is that having some design goals and limitations will make this a better module and help make it manageable to support in the future, even if it means denying some requests.

**Comment by roguedevjake** [comment]
> I also have an "each roll is sacred" policy which means that damage rolls aren't rolled "in case".

Keep in mind I am not asking for the roll to be made automatically, more that the confirmation step isn't necessary for the GM as when you click confirm, you are rolling damage. 

A hotkey to confirm would be more useful than rolling damage imo. 

My point is not to automate anything, it is just that it is an extra click/step that doesn't exist in a physical game, foundry's default or elsewhere. (just incase you are misunderstanding my intentions).

**Comment by kaelad02** [comment]
I had to reread the initial post to understand. I too wouldn't want hits to auto-confirm but I understand that's not what this is asking for. More like a small UX improvement by reducing the number of clicks for GM attacks.

**Comment by teroparvinen** [comment]
Managed to come up with a clean solution for this.

**Comment by roguedevjake** [comment]
> Managed to come up with a clean solution for this.

The same solution I suggested I see :) 

But thanks, makes a big difference and will save a lot of clicking.

**Comment by teroparvinen** [comment]
@roguedevjake for what it's worth, I referred to a clean technical solution, one that does not mess with the general customizability of the system and provides a working UI in all scenarios. Nothing wrong with the design idea of your original request after a bit of convincing. :) Thanks for the idea!
